return {
    -- Debug Settings
    Debug = false, -- Set to true to enable debug messages
    
    -- Core Settings
    CooldownDuration = 60000, -- Cooldown duration in milliseconds
    
    -- UI Settings
    Notifications = "qb", -- Options: "ps", "qb", "k5", "ox"
    ProgressBar = "qb", -- Options: "qb", "ox"
    
    -- Minigame Settings
    Minigame = {
        Enabled = true, -- Set to false to disable minigames completely
        Type = "boii", -- Options: "ps-ui", "boii"
        Settings = {
            -- PS-UI Circle settings
            Circles = 3, -- Number of circles for ps-ui
            Time = 10, -- Time in seconds for ps-ui
            
            -- BOII Button Mash settings
            Style = "default", -- Style template for boii
            Difficulty = 10 -- Difficulty for boii
        }
    },
    
    -- Gameplay Settings
    AttackChance = 20, -- Chance a dog will spawn and attack the player
    RequiredItem = "gloves",
    
    -- Reward Items
    Items = {
        {item = "tosti", probability = 50},
        {item = "metalscrap", probability = 30},
        {item = "iron", probability = 15},
        {item = "plastic", probability = 5},
    },
    
    -- Garbage Props
    GarbageProps = {
        'prop_bin_01a',
        'prop_bin_03a',
        'prop_bin_04a',
        'prop_bin_05a',
        'prop_bin_06a',
        'prop_bin_07a',
        'prop_bin_07b',
        'prop_bin_07c',
        'prop_bin_07d',
        'prop_bin_08a',
        'prop_bin_08open',
        'prop_bin_09a',
        'prop_bin_10a',
        'prop_bin_10b',
        'prop_bin_11a',
        'prop_bin_11b',
        'prop_bin_12a',
        'prop_bin_13a',
        'prop_bin_14a',
        'prop_bin_14b',
        'prop_dumpster_01a',
        'prop_dumpster_02a',
        'prop_dumpster_02b',
        'prop_dumpster_3a',
        'prop_dumpster_4a',
        'prop_dumpster_4b',
        'prop_skip_01a',
        'prop_skip_02a',
        'prop_skip_03',
        'prop_skip_04',
        'prop_skip_05a',
        'prop_skip_06a',
        'prop_skip_07a',
        'prop_skip_08a',
        'prop_skip_10a',
        'prop_trash_01a',
        'prop_trash_02a',
        'prop_trash_03a',
        'prop_trash_04a',
        'prop_trash_05a',
        'prop_trash_06a',
        'prop_trash_07a',
        'prop_trash_08a',
        'prop_trash_basket_01',
        'prop_trash_bin_01a',
        'prop_trash_bin_02a',
        'prop_trash_bin_03a',
        'prop_trash_bin_04a',
        'prop_trash_bin_05a',
        'prop_trash_bin_06a',
        'prop_trash_bin_07a',
        'prop_trash_bin_07b',
        'prop_trash_bin_07d',
        'prop_trash_bin_08a',
        'prop_trash_pile_01a',
        'prop_trash_pile_02a',
        'prop_trash_pile_03a',
        'prop_trash_pile_04a',
        'prop_rub_binbag_01',
        'prop_rub_binbag_sd_01',
        'prop_rub_binbag_sd_02',
        'prop_rub_binbag_sd_03',  
        'prop_rub_bottle_01',
        'prop_rub_bottle_02',
        'prop_rub_bottle_03',
        'prop_rub_bottle_04',
        'prop_cardbordbox_01a',
        'prop_cardbordbox_02a',
        'prop_cardbordbox_03a',
        'prop_cardbordbox_04a',
        'prop_debris_bin_01a',
        'prop_debris_bin_03a',
        'prop_oil_drum_01',
        'prop_oil_drum_02',
        'prop_oil_drum_03',
        'prop_oil_drum_04',
        'prop_oil_drum_05',
        'prop_wheeliebin_01a',
        'prop_wheeliebin_02a',
        'prop_wheeliebin_03a',
        'prop_wheeliebin_05a',
        'prop_rub_binbag_03',
        'prop_rub_binbag_04',
        'prop_rub_binbag_05',
        'prop_rub_binbag_06',
        'prop_rub_binbag_07',
        'prop_rub_binbag_08',
        'prop_rub_binbag_09',
        'prop_rub_cage01a',
        'prop_rub_cage01b',
        'prop_rub_cage01c',
        'prop_rub_cage01d',
        'prop_rub_cage01e',
        'prop_rub_carwreck_2',
        'prop_rub_carwreck_3',
        'prop_rub_carwreck_5',
        'prop_rub_carwreck_7',
        'prop_rub_carwreck_8',
        'prop_rub_carwreck_9',
        'prop_rub_carwreck_10',
        'prop_rub_carwreck_11',
        'prop_rub_carwreck_12',
        'prop_rub_carwreck_13',
        'prop_rub_carwreck_14',
        'prop_rub_carwreck_15',
        'prop_rub_carwreck_16',
        'prop_rub_carwreck_17',
        'prop_rub_cont_01a',
        'prop_rub_cont_01b',
        'prop_rub_cont_01c',
        'prop_rub_flotsam_01',
        'prop_rub_flotsam_02',
        'prop_rub_flotsam_03',
        'prop_rub_litter_01',
        'prop_rub_litter_02',
        'prop_rub_litter_03',
        'prop_rub_litter_04',
        'prop_rub_litter_05',
        'prop_rub_litter_06',
        'prop_rub_litter_07',
        'prop_rub_litter_08',
        'prop_rub_litter_09',
        'prop_rub_litter_10',
        'prop_rub_pile_01',
        'prop_rub_pile_02',
        'prop_rub_pile_03',
        'prop_rub_pile_04',
        'prop_rub_pile_05',
        'prop_rub_planks_01',
        'prop_rub_planks_02',
        'prop_rub_planks_03',
        'prop_rub_planks_04',
        'prop_rub_railwreck_1',
        'prop_rub_railwreck_2',
        'prop_rub_railwreck_3',
        'prop_rub_scrap_02',
        'prop_rub_scrap_03',
        'prop_rub_scrap_04',
        'prop_rub_scrap_05',
        'prop_rub_scrap_06',
        'prop_rub_scrap_07',
        'prop_bin_02a',
    }
}